version: '3'
services:
  react:
    build: .
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      #REACT_APP_BASE_API_URL: https://develop.dte.e2l.dev/
      REACT_APP_BASE_API_URL: http://localhost/
    volumes:
       - ./:/usr/src/